### ISSUE TITLE
Voice Com not available in latest version

### ISSUE THREAD

**Issue by sandikata** [ArmynC/ArminC-AutoExec#11]
Voice comm (previously bind T) not exist on latest version, is it there any way to enable it ?

## Checklist

- [ ] I searched the [current issues](https://github.com/ArmynC/ArminC-AutoExec/issues) and the feature is not known.
- [ ] I am mostly sure that the feature will bring more good than harm.

**Comment by armync** [comment]
Sure, in the recent updates, it was moved back to its older placement, which should be the key 'V' or 'scancode25'.

For further reference, you may check the bindings: https://github.com/ArmynC/ArminC-AutoExec?tab=readme-ov-file#binds

Don't hesitate to ask anything else if needed!

**Comment by sandikata** [comment]
Closing this one
