### ISSUE TITLE
Config is not executed

### ISSUE THREAD

**Issue by crashzk** [ArmynC/ArminC-AutoExec#5]
No message on the console, nothing happens

**Comment by armync** [comment]
From the looks of it on my computer, everything is fine. Are you sure you followed all the installation steps (inc. the newer folder path; e.g. `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg`)? 

Also, be aware that the autoexecs sometimes aren't so _automatic_ anymore, so you need to exec it manually in the console. However, after the release of the game (out of the beta state), it is still possible that the launching method has changed, although I haven't yet seen any changes.

![console](https://github.com/ArmynC/ArminC-AutoExec/assets/16375271/38c47157-d7bf-4f8f-b942-159133c15d83)
![path](https://github.com/ArmynC/ArminC-AutoExec/assets/16375271/cd884e34-5f38-44a4-8563-5b924d8f6e2e)

**Comment by crashzk** [comment]
As you can see nothing, even running the command manually.

![20230929144207_1](https://github.com/ArmynC/ArminC-AutoExec/assets/32937653/95e584e4-ab15-4209-8daa-f9bcd5c7a199)

![image](https://github.com/ArmynC/ArminC-AutoExec/assets/32937653/400d09aa-3a33-4ca6-b9ca-020c1ef86f49)

**Comment by crashzk** [comment]
Sorry, now that I see it, the path is different, I didn't notice the `game` folder.

Anyway, everything works now, thank you!
