### ISSUE TITLE
AIM BOT

### ISSUE THREAD

**Issue by NovaNinja969** [ArmynC/ArminC-AutoExec#9]
maybe add AIM Bot

**Comment by armync** [comment]
Uhm, are you talking about some sort of aim training config? Else, if you request some cheat integration, one should break sv_cheats cvar😆 otherwise, can't do :(

**Comment by NovaNinja969** [comment]
ok sorry I fought this was a hack😅

**Comment by NovaNinja969** [comment]
but love it!
